export const Films = [
    {
        id: 1,
        Image: 'assets/The_Walking_Dead.jpg',
        Title: 'Walking Dead',
        Year: "1999",
        Nation: 'USA',
        Card_Img: './assets/The_Walking_Dead_Card.jpg',
        Imbd: 5.2,
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/sfAc2U20uyg',
        Release: "July 7, 2010",
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 2,
        Image: 'assets/Stranger_Thing.jpg',
        Title: 'Stranger Thing',
        Year: "2000",
        Nation: 'USA',
        Imbd: 2.2,
        Card_Img: './assets/Stranger_Thing_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/sBEvEcpnG7k',
        Release: "July 4, 2018",
        Director: "Dinh Gia Bao, Elizabeth III"

    },
    {
        id: 3,
        Image: './assets/Harry_Potter.jpg',
        Title: 'Harry Potter',
        Year: "2001",
        Nation: 'USA',
        Imbd: 8.2,
        Card_Img: './assets/Harry_Potter_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/jDIatWZ8nfY',
        Release: "September 21, 2022",
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 4,
        Image: './assets/Breaking_Bad_Poster.jpg',
        Title: 'Breaking Bad',
        Year: "2002",
        Nation: 'USA',
        Imbd: 9.2,
        Card_Img: './assets/Breaking_Bad_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/HhesaQXLuRY',
        Release: 'September 10, 2020',
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 5,
        Image: './assets/Suzume.jpg',
        Title: 'Suzume no kijimori',
        Year: "2023",
        Nation: 'NiHon',
        Imbd: 8.2,
        Card_Img: './assets/Suzume_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/xQ4_c8JfuzI',
        Release: 'December 18, 2002',
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 6,
        Image: './assets/Your_Name_Poster.jpg',
        Title: 'Your Name',
        Year: "2020",
        Nation: 'Nihon',
        Imbd: 9.2,
        Card_Img: './assets/Your_Name_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/_mifHzxFNQ4',
        Release: "January 12, 2012",
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 7,
        Image: './assets/sex_education.jpg',
        Title: 'Sex Education',
        Year: "2016",
        Nation: 'USA',
        Imbd: 5.2,
        Card_Img: './assets/Sex_Education_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',

        clip: 'https://www.youtube.com/embed/Hd2ldTR-WpI',
        Release: "December 18, 2002",
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 8,
        Image: './assets/Peaky_Blinders.jpg',
        Title: 'Peaky Blinders',
        Year: "2022",
        Nation: 'USA',
        Imbd: 6.2,
        Card_Img: './assets/Peaky_Blinders_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/oVzVdvGIC7U',
        Release: "December 18, 2002",
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 9,
        Image: 'assets/Arcane.jpg',
        Title: 'Arcane',
        Year: "2022",
        Nation: 'USA',
        Imbd: 3.2,
        Card_Img: './assets/Arcane_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/fXmAurh012s',
        Release: "December 18, 2002",
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 10,
        Image: './assets/Komi-Cant-Communicate.jpg',
        Title: "Komi Can't Communicate",
        Year: "2022",
        Nation: 'USA',
        Imbd: 3.2,
        Card_Img: 'assets/Komi_Card2.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/tLdLTSnmnoA',
        Release: "December 18, 2002",
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 11,
        Image: './assets/One-Piece.jpg',
        Title: 'One piece',
        Year: "2022",
        Nation: 'USA',
        Imbd: 3.2,
        Card_Img: 'assets/One_Piece_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/S8_YwFLCh4U',
        Release: "December 18, 2002",
        Director: "Dinh Gia Bao, Elizabeth III"
    },
    {
        id: 12,
        Image: './assets/Sonic.jpg',
        Title: 'Sonic The Hedgedog',
        Year: "2022",
        Nation: 'USA',
        Imbd: 3.2,
        Card_Img: 'assets/Sonic_Card.jpg',
        details: 'Presentations are essential tools for demonstrations, lectures, speeches, reports, and other purposes. Commonly presented in front of the audience, presentations are very important for brand marketing.',
        clip: 'https://www.youtube.com/embed/szby7ZHLnkA',
        Release: "December 18, 2002",
        Director: "Dinh Gia Bao, Elizabeth III"
    }];